name: Kickball
favicon: null
layout_spectrum: 0.411518789594993
typography_spectrum: 0.8106041965074837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0742605128325522
  lightness: 0.9828862540889531
  saturation: 0.1803321954794228
  rhythmicContrast: 0.4143478344194591
purpose: []
